<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>ufoahc mobile</title>
    <link rel="shortcut icon" href="/ico/common/favicon.ico">
    <link rel="stylesheet" href="/css/common/base-rest.min.css" type="text/css" />
    <script src="/js/common/jquery-2.2.4.min.js"></script>
    <script src="/js/common/main.min.js"></script>
    <script>
        function selfAdaption(correctScale){var dpr,rem,scale;var docEl=document.documentElement;var fontEl=document.createElement('style');var metaEl=document.querySelector('meta[name="viewport"]');dpr=window.devicePixelRatio||1;rem=$(window).width()*dpr/10;scale=1/dpr;if(!window.myWidth){window.myWidth=$(window).width()}rem=window.myWidth*dpr/10;if(correctScale){scale=correctScale}else{scale=1/dpr}metaEl.setAttribute('content','width='+dpr*window.myWidth+',initial-scale='+scale+',maximum-scale='+scale+', minimum-scale='+scale+',user-scalable=yes');docEl.setAttribute('data-dpr',dpr);docEl.firstElementChild.appendChild(fontEl);fontEl.innerHTML='html{font-size:'+rem+'px !important;}';window.rem2px=function(v){v=parseFloat(v);return v*rem};window.px2rem=function(v){v=parseFloat(v);return v/rem};window.dpr=dpr;window.rem=rem}window.myWidth=0;selfAdaption();
    </script>
</head>
<body>
<div>这里是顶部</div>
<hr>
<div>
    <?php include $_content; ?>
</div>
<hr>
<div>这里是底部</div>
</body>
</html>