<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ufoahc</title>
    <link rel="shortcut icon" href="/ico/common/favicon.ico">
    <link rel="stylesheet" href="/css/common/base-rest.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/common/main.min.css" type="text/css" />
    <script src="/js/common/jquery-2.2.4.min.js"></script>
    <script src="/js/common/main.min.js"></script>
</head>
<body>
<h1>这里是顶部</h1>
<hr>
<div>
    <?php include $_content; ?>
</div>
<hr>
<h1>这里是底部</h1>
</body>
</html>